# Generated by Django 5.1.6 on 2025-04-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_academico', '0002_alter_materia_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
