# Generated by Django 5.1.6 on 2025-04-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_academico', '0003_libro_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='modelo_parcial',
            field=models.FileField(blank=True, null=True, upload_to='modelo/'),
        ),
    ]
