# Generated by Django 5.1.6 on 2025-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_academico', '0004_libro_modelo_parcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='fecha_final2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
