# Generated by Django 5.1.6 on 2025-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_academico', '0005_progreso_fecha_final2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='fecha_tp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
